"""add role and status fields

Revision ID: 3c8fde253126
Revises: 
Create Date: 2025-08-29 19:48:03.504829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8fde253126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('places', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=True))
    op.create_foreign_key(None, 'places', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'USER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'status')
    op.drop_column('places', 'owner_id')
    # ### end Alembic commands ###
