"""Add category table and category_id to Place

Revision ID: 614a73d7301e
Revises: 3c8fde253126
Create Date: 2025-08-30 19:46:29.210133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614a73d7301e'
down_revision: Union[str, Sequence[str], None] = '3c8fde253126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Check if table exists (SQLite doesn't support IF NOT EXISTS in Alembic)
    conn = op.get_bind()
    tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='categories';").fetchall()
    if not tables:
        op.create_table(
            'categories',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('name', sa.String, unique=True, nullable=False),
            sa.Column('description', sa.String, default=""),
            sa.Column('icon_url', sa.String, default=""),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True)
        )

    # Add category_id to places using batch mode
    with op.batch_alter_table("places") as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer, nullable=True))
        batch_op.create_foreign_key(
            "fk_places_category", "categories", ["category_id"], ["id"]
        )
    
    # Drop old string column
    with op.batch_alter_table("places") as batch_op:
        batch_op.drop_column("category")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'category_id')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
