"""Add city, region, country, email, payment_methods to Place

Revision ID: ef1250a63116
Revises: c866bfdea350
Create Date: 2025-09-01 13:20:20.202441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1250a63116'
down_revision: Union[str, Sequence[str], None] = 'c866bfdea350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)
    op.add_column('places', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('city', sa.String(), nullable=True))
    op.add_column('places', sa.Column('region', sa.String(), nullable=True))
    op.add_column('places', sa.Column('country', sa.String(), nullable=True))
    op.add_column('places', sa.Column('email', sa.String(), nullable=True))
    op.add_column('places', sa.Column('payment_methods', sa.JSON(), nullable=True))
    op.add_column('places', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'places', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_column('places', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('subcategory', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'is_active')
    op.drop_column('places', 'is_featured')
    op.drop_column('places', 'payment_methods')
    op.drop_column('places', 'email')
    op.drop_column('places', 'country')
    op.drop_column('places', 'region')
    op.drop_column('places', 'city')
    op.drop_column('places', 'subcategory_id')
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
